### ISSUE TITLE
Inventory Management Module

### ISSUE THREAD

**Issue by francis450** [francis450/InventoryManagement#6]
### Develop functionalities for managing inventory items.
- Users can add new inventory items with details such as name, quantity, and price.
- Users can edit existing inventory items.
- Users can delete inventory items.
- Inventory items can be searched by name or category.

**Comment by Bree-Wanjiru** [comment]
to add supplier, products and supplier to products

**Comment by Bree-Wanjiru** [comment]
added products

**Comment by Bree-Wanjiru** [comment]
added supplier

**Comment by Bree-Wanjiru** [comment]
added  supplier to products

**Comment by Bree-Wanjiru** [comment]
Done
